### ISSUE TITLE
Update Chrome Extension manfiest.json to V3

### ISSUE THREAD

**Issue by aeksco** [aeksco/react-typescript-web-extension-starter#1]
See guide here: https://developer.chrome.com/extensions/migrating_to_manifest_v3

**Comment by punithbm** [comment]
Hi, @aeksco  Please review this [PR](https://github.com/aeksco/react-typescript-web-extension-starter/pull/46) for the manifest json version 3

**Comment by aeksco** [comment]
Thanks again @punithbm - closing this out 🎉
