### ISSUE TITLE
Can you make this repo a template?

### ISSUE THREAD

**Issue by perryraskin** [aeksco/react-typescript-web-extension-starter#37]
Would be great to have the option to start a chrome extension project with this repo as a template! Thanks :D

**Comment by aeksco** [comment]
@perryraskin Sorry for the delay - I love the idea of making this a template repo. I'm going to clean up 1-2 little things first but I should have some time in the next week to make that change - thanks for your interest in the project!

**Comment by aeksco** [comment]
Resolved
