### ISSUE TITLE
Missing .nvmrc file

### ISSUE THREAD

**Issue by Kuboczoch** [aeksco/react-typescript-web-extension-starter#39]
As a new user of your template, I see that there is no `.nvmrc` file that should contain your node version to make sure that we are using the same one.

If you can tell me which version you are using I can even make a PR for you to help you with that.

**Comment by aeksco** [comment]
@Kuboczoch Thanks for opening this issue! I'm using `16.13.0` right now which it the latest Node LTS release for MacOS. Please feel free to open a PR with this update, thanks for flagging!
