### ISSUE TITLE
Use of ViteJs instead of Webpack

### ISSUE THREAD

**Issue by punithbm** [aeksco/react-typescript-web-extension-starter#47]
@aeksco  Thanks for an extension starter kit. 

We have forked your repo - react-typescript chrome extension and updated the webpack bundler to use [viteJs](https://vitejs.dev/)  instead.

Forked Repo URL - [Designstring/react-typescript-web-extension-starter](https://github.com/DesignString/react-typescript-web-extension-starter) 

Whenever you get a chance please check and see if the forked repo can be included under the notable forks section in the ReadMe file. So that anyone looking to use the boilerplate with [viteJs](https://vitejs.dev/) combination can utilize it. 

Thank you

**Comment by aeksco** [comment]
Hi @punithbm ! Yeah please feel free to open a PR adding your repo under `notable forks` - I'll keep an eye out for the PR, thanks again for your continued interest in this project!

**Comment by punithbm** [comment]
Thank you. Raised the PR #48

**Comment by aeksco** [comment]
Thank you! Closing this out :+1:
