### ISSUE TITLE
Verify Brave browser support

### ISSUE THREAD

**Issue by aeksco** [aeksco/react-typescript-web-extension-starter#8]
[Brave](https://brave.com/) should probably work out of the box since it's Chromium based, but we should make sure that this project supports it as a build target.

**Comment by AlexRAV** [comment]
Sure, it work's.
![brave_ext_template1](https://user-images.githubusercontent.com/13298791/79121669-06d47080-7dc0-11ea-8e31-0fa468836f76.gif)

**Comment by aeksco** [comment]
@AlexRAV Thanks for much for verifying! Glad it works :D 

I'm going to leave this ticket open as a reminder to ass `Brave` to the list of supported browsers in `README.md` - need to update the cover image as well.

Thanks again for checking, appreciate the support!

**Comment by aeksco** [comment]
Added notes to `README.md` detailing support for Brave in PR #11 - closing this issue
